# @gitlab
# ------------------------------------------------------------------------------------
# @link https://docs.gitlab.com/ee/ci/variables/README.html       Gitlab 默认参数地址
# @link https://docs.gitlab.com/runner/install/                   Gitlab Runner 安装文档
# @link https://hub.docker.com/r/gitlab/gitlab-ce/
# ------------------------------------------------------------------------------------
# @help gitlab-runner无法调用docker命令时，为gitlab-runner增加权限 usermod -aG docker gitlab-runner
# @help gitlab-runner调用docker push无权限时，可以 su gitlab-runner \ docker login

stages:
  - build
  - deploy

variables:
  PROJECT_NAME: swoft
  REGISTRY_URL: registry-docker.org

build_docker:
  stage: build
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
  only:
    - tags
    - master
  tags:
    - prod

deploy_docker:
  stage: deploy
  script:
    - docker stack deploy -c deploy.yml --with-registry-auth $PROJECT_NAME
  only:
    - tags
  tags:
    - prod
