language: php

sudo: required

env:
  SW_VERSION: 4.2.9

php:
  - 7.1
  - 7.2

services:
  - mysql
  - redis
  - docker

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - bash test/install_swoole.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add test/ci.ini

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mv .env.example .env
  - composer update -o

script:
  - ./vendor/bin/phpstan analyse app
  - composer test

cache:
  directories:
    - "$HOME/.composer/cache/files"
